# Import Dataset

In [8]:
import numpy as np
import pandas as pd

df = pd.read_csv("MI7_GROUNDWATERSCHEME_ASSAM.csv")
df.head()

,serial_no,state_name,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
0,1,ASSAM,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,No
1,2,ASSAM,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,No
2,3,ASSAM,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Yes
3,4,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
4,5,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,No

In [9]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57303 entries, 0 to 57302
Data columns (total 64 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   serial_no                           57303 non-null  int64
 1   state_name                          57303 non-null  object
 2   district_name                       57303 non-null  object
 3   block_tehsil_name                   57303 non-null  object
 4   village_name                        57303 non-null  object
 5   latitude                            57303 non-null  float64
 6   longitude                           57303 non-null  float64
 7   s_no_of_scheme                      57303 non-null  int64
 8   scheme_type                         57303 non-null  object
 9   dugwell_type                        809 non-null    object
 10  tubewell_type                       56494 non-null  object
 11  ownership                           57303 non-null  object
 12  khasra_number                       24023 non-null  object
 13  location_particulars                51320 non-null  object
 14  total_owners_holding                57303 non-null  float64
 15  social_status                       41361 non-null  object
 16  gender                              41361 non-null  object
 17  commissioning_year                  57303 non-null  object
 18  scheme_depth                        57303 non-null  float64
 19  scheme_diameter                     54149 non-null  float64
 20  scheme_bore_depth                   57303 non-null  float64
 21  nearest_scheme_distance             57303 non-null  float64
 22  construction_cost                   57303 non-null  float64
 23  machinery_cost                      57303 non-null  float64
 24  maintenance_cost                    57303 non-null  float64
 25  finance_source1                     41334 non-null  object
 26  finance_source2                     33615 non-null  object
 27  construction_subsidy                57303 non-null  float64
 28  machinery_subsidy                   57303 non-null  float64
 29  scheme_status                       57303 non-null  object
 30  not_in_use_years                    6109 non-null   float64
 31  status_reason_temporarily           5342 non-null   object
 32  status_reason_permanently           767 non-null    object
 33  water_distribution_method           56536 non-null  object
 34  lifting_device_type                 56555 non-null  object
 35  energy_source                       56555 non-null  object
 36  horse_power_of_lifting_device       55384 non-null  float64
 37  pump_operating_days_kharif_season   55396 non-null  float64
 38  pump_operating_days_rabi_season     55396 non-null  float64
 39  pump_operating_days_perennial_crop  55396 non-null  float64
 40  pump_operating_days_other_season    55396 non-null  float64
 41  avg_pumping_per_day_kharif_season   55396 non-null  float64
 42  avg_pumping_per_day_rabi_season     55396 non-null  float64
 43  avg_pumping_per_day_perennial_crop  55396 non-null  float64
 44  avg_pumping_per_day_other_season    55395 non-null  float64
 45  located_in_command_area             57303 non-null  object
 46  name_of_mmi_project                 161 non-null    object
 47  scheme_in_command_area_reason       146 non-null    object
 48  only_recharge_ground_water          57303 non-null  object
 49  culturable_command_area             57303 non-null  float64
 50  ipc_kharif_season                   57303 non-null  float64
 51  ipc_rabi_season                     57303 non-null  float64
 52  ipc_perennial_crop                  57303 non-null  float64
 53  ipc_other_season                    57303 non-null  float64
 54  ipc_total                           57303 non-null  float64
 55  ipu_kharif_season                   57303 non-null  float64
 56  ipu_rabi_season                     57303 non-null  float64
 57  ipu_perennial_crop                  57303 non-null  float64
 58  ipu_other_season                    57303 non-null  float64
 59  ipu_total                           57303 non-null  float64
 60  under_utilised_selection            51264 non-null  object
 61  under_utilisation_reason            8546 non-null   object
 62  drinking_water_purpose              57303 non-null  object
 63  captured_in_previous_census         56466 non-null  object
dtypes: float64(33), int64(2), object(29)
memory usage: 28.0+ MB

In [10]:
df.describe()

,serial_no,latitude,longitude,s_no_of_scheme,total_owners_holding,scheme_depth,scheme_diameter,scheme_bore_depth,nearest_scheme_distance,construction_cost,...,ipc_kharif_season,ipc_rabi_season,ipc_perennial_crop,ipc_other_season,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total
count,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,54149.000000,57303.000000,57303.000000,5.730300e+04,...,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000
mean,28652.000000,26.314407,91.459174,11.900215,1.557596,27.468942,85.076435,0.231128,205.604155,1.577646e+05,...,2.155317,1.941574,0.174485,0.375635,4.647010,1.801973,1.587813,0.153559,0.288059,3.831123
std,16542.095575,0.422958,1.447504,17.412754,45.359578,17.318626,405.582533,5.276484,180.272319,6.753971e+05,...,4.032863,2.717230,2.885272,4.587932,8.718665,3.275841,1.934804,2.850640,4.536090,7.500362
min,1.000000,24.269978,89.702887,1.000000,0.000000,0.030000,0.000000,0.000000,0.010000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14326.500000,26.129345,90.186019,2.000000,0.000000,18.000000,3.000000,0.000000,100.000000,1.000000e+04,...,0.666000,1.000000,0.000000,0.000000,2.000000,0.500000,1.000000,0.000000,0.000000,1.800000
50%,28652.000000,26.288032,91.030726,6.000000,1.000000,24.000000,80.000000,0.000000,125.000000,1.500000e+04,...,1.500000,1.500000,0.000000,0.000000,3.500000,1.000000,1.200000,0.000000,0.000000,3.000000
75%,42977.500000,26.437511,92.381378,14.000000,2.000000,35.000000,100.000000,0.000000,300.000000,3.500000e+04,...,2.100000,2.000000,0.000000,0.200000,5.000000,2.000000,2.000000,0.000000,0.100000,4.400000
max,57303.000000,27.972524,95.889462,221.000000,9000.000000,800.000000,35000.000000,450.000000,5001.000000,5.000000e+07,...,250.000000,122.000000,250.000000,750.000000,750.000000,250.000000,122.000000,250.000000,750.000000,750.000000

In [11]:
df.describe(include='object')

,state_name,district_name,block_tehsil_name,village_name,scheme_type,dugwell_type,tubewell_type,ownership,khasra_number,location_particulars,...,lifting_device_type,energy_source,located_in_command_area,name_of_mmi_project,scheme_in_command_area_reason,only_recharge_ground_water,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
count,57303,57303,57303,57303,57303,809,56494,57303,24023,51320,...,56555,56555,57303,161,146,57303,51264,8546,57303,56466
unique,1,34,227,8393,2,4,4,6,2180,20021,...,5,7,2,24,4,2,2,6,2,2
top,ASSAM,Dhubri,Mandia,Geramari Pt.I,Tube well,Dug well Pucca,Shallow Tube well,Owned by individual farmer,na,na,...,Centrifugal Pump,Diesel,No,JAMUNA IRRIGATION SCHEME,Other reasons,No,No,Any other reason,No,No
freq,57303,14841,3429,221,56494,477,47322,41242,8265,2678,...,36890,27323,57157,55,76,56143,42718,8138,55498,55322

In [12]:
cols = [col for col in df.columns]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: serial_no
Data type: int64
Unique values: 57303
Missing values: 0
serial_no
57303    1
1        1
2        1
3        1
4        1
5        1
6        1
57287    1
57286    1
57285    1
57284    1
57283    1
57282    1
57281    1
57280    1
Name: count, dtype: int64

==================================================
Column: state_name
Data type: object
Unique values: 1
Missing values: 0
state_name
ASSAM    57303
Name: count, dtype: int64

==================================================
Column: district_name
Data type: object
Unique values: 34
Missing values: 0
district_name
Dhubri        14841
Barpeta       10315
Marigaon       5020
Bongaigaon     2922
Kamrup         2285
Goalpara       2273
Nagaon         2160
Darrang        2104
Golaghat       1272
Lakhimpur      1201
Kokrajhar      1149
Cachar         1067
Sonitpur       1064
Tinsukia        962
Hojai           927
Name: count, dtype: int64

==================================================
Column: block_tehsil_name
Data type: object
Unique values: 227
Missing values: 0
block_tehsil_name
Mandia              3429
Debitola            2475
Gauripur            2291
Mahamaya            2114
Pakabetbari         1791
Laharighat          1780
Rupshi              1473
Ruposhi             1292
Agomani             1273
Chenga              1194
Mayang              1159
Birshing-Jarua      1118
Dalgaon-Sialmari    1098
Barpeta              988
Nayeralga            920
Name: count, dtype: int64

==================================================
Column: village_name
Data type: object
Unique values: 8393
Missing values: 0
village_name
Geramari Pt.I         221
Satra Kanara N.C.     200
Beguntali             165
Geramari Pt.Vi        120
Dalaner Alga Pt.Ii    112
Asharikandi           111
Majar Char N.C.       105
Sajuarkuti            105
Kawanbari             105
Aminerchor            103
Kachumara N.C.         97
Jhalar Alga Pt.I       92
Bowalguri              88
Alomganj Pt.Iv         87
Bouserkuti             86
Name: count, dtype: int64

==================================================
Column: latitude
Data type: float64
Unique values: 54532
Missing values: 0
latitude
26.313813    13
26.034514    12
26.448284    12
26.238670    10
24.930547    10
26.976792     9
26.102358     9
26.251230     9
26.264147     9
26.286045     9
26.465390     9
26.167782     8
26.006658     8
26.413214     8
27.138448     8
Name: count, dtype: int64

==================================================
Column: longitude
Data type: float64
Unique values: 54650
Missing values: 0
longitude
90.480240    13
90.176807    12
92.545021    12
92.162062    10
92.536352    10
90.159008    10
92.738888    10
90.167788    10
90.160179    10
94.727689     9
89.975941     9
90.166617     8
90.171593     8
93.063650     8
95.206606     8
Name: count, dtype: int64

==================================================
Column: s_no_of_scheme
Data type: int64
Unique values: 221
Missing values: 0
s_no_of_scheme
1     8817
2     6046
3     4671
4     3821
5     3241
6     2808
7     2491
8     2205
9     1965
10    1762
11    1588
12    1414
13    1257
14    1137
15    1039
Name: count, dtype: int64

==================================================
Column: scheme_type
Data type: object
Unique values: 2
Missing values: 0
scheme_type
Tube well    56494
Dug well       809
Name: count, dtype: int64

==================================================
Column: dugwell_type
Data type: object
Unique values: 4
Missing values: 56494
dugwell_type
NaN                  56494
Dug well Pucca         477
Dug well Kutcha        228
Dug-cum-bore well       75
Others                  29
Name: count, dtype: int64

==================================================
Column: tubewell_type
Data type: object
Unique values: 4
Missing values: 809
tubewell_type
Shallow Tube well    47322
Medium Tube well      7761
Deep Tube well        1389
NaN                    809
Artesian Well           22
Name: count, dtype: int64

==================================================
Column: ownership
Data type: object
Unique values: 6
Missing values: 0
ownership
Owned by individual farmer    41242
Govt. Owned                   10014
Owned by Group of farmers      3242
Others                         2582
Co-Operative Owned              138
Panchayat Owned                  85
Name: count, dtype: int64

==================================================
Column: khasra_number
Data type: object
Unique values: 2180
Missing values: 33280
khasra_number
NaN    33280
na      8265
Na      2906
1       2111
NA      1317
0        572
na       562
2        444
3        311
4        272
NS       258
5        240
6        224
N A      193
7        184
Name: count, dtype: int64

==================================================
Column: location_particulars
Data type: object
Unique values: 20021
Missing values: 5983
location_particulars
NaN                  5983
na                   2678
A                    1409
in filled             736
near home             524
near road             511
near house            477
NA                    463
Na                    433
NEAR PADDY FIELD      353
NEAR LP SCHOOL        342
near JJM PHE          314
in paddy              310
NEAR PWD ROAD         267
0                     256
Name: count, dtype: int64

==================================================
Column: total_owners_holding
Data type: float64
Unique values: 305
Missing values: 0
total_owners_holding
1.00    16425
0.00    16061
2.00     9209
3.00     2053
1.50     1697
4.00     1616
0.50     1018
5.00      967
0.80      551
1.33      438
0.40      434
1.20      429
0.53      414
0.66      347
6.00      341
Name: count, dtype: int64

==================================================
Column: social_status
Data type: object
Unique values: 4
Missing values: 15942
social_status
Others             31977
NaN                15942
OBC                 4455
Scheduled-tribe     2975
Scheduled-caste     1954
Name: count, dtype: int64

==================================================
Column: gender
Data type: object
Unique values: 3
Missing values: 15942
gender
Male           40784
NaN            15942
Female           565
Transgender       12
Name: count, dtype: int64

==================================================
Column: commissioning_year
Data type: object
Unique values: 6
Missing values: 0
commissioning_year
Up to 2018-2019     22215
During 2019-2020    11750
During 2020-2021     9626
During 2021-2022     7129
During 2022-2023     3534
During 2023-2024     3049
Name: count, dtype: int64

==================================================
Column: scheme_depth
Data type: float64
Unique values: 448
Missing values: 0
scheme_depth
20.0    8014
24.0    6816
45.0    5531
35.0    5347
15.0    3782
25.0    3542
18.0    2655
30.0    2534
12.0    1511
21.0    1409
16.0    1402
22.0     996
13.0     937
17.0     833
70.0     739
Name: count, dtype: int64

==================================================
Column: scheme_diameter
Data type: float64
Unique values: 296
Missing values: 3154
scheme_diameter
100.00    13635
75.00      6823
80.00      5865
150.00     5518
0.08       3298
NaN        3154
0.10       2811
0.15       2509
0.07       1430
76.00      1178
110.00     1058
76.20       792
101.60      746
3.00        624
0.30        537
Name: count, dtype: int64

==================================================
Column: scheme_bore_depth
Data type: float64
Unique values: 72
Missing values: 0
scheme_bore_depth
0.00      57028
45.00        42
35.00        33
30.00        17
20.00        16
0.45         15
50.00        14
70.00        10
80.00        10
75.00         9
100.00        6
15.00         6
10.00         5
29.00         5
25.00         5
Name: count, dtype: int64

==================================================
Column: nearest_scheme_distance
Data type: float64
Unique values: 277
Missing values: 0
nearest_scheme_distance
100.0    13341
500.0     8554
200.0     8137
50.0      5052
300.0     3466
150.0     3059
400.0     1576
60.0      1357
30.0      1237
20.0      1236
250.0     1074
80.0      1017
120.0      875
70.0       542
10.0       527
Name: count, dtype: int64

==================================================
Column: construction_cost
Data type: float64
Unique values: 1271
Missing values: 0
construction_cost
10000.0     6166
12000.0     4642
15000.0     3736
20000.0     3708
5000.0      2847
8000.0      2216
6000.0      1850
25000.0     1845
30000.0     1618
35000.0     1329
9000.0      1238
606000.0    1018
100000.0     768
40000.0      701
7000.0       656
Name: count, dtype: int64

==================================================
Column: machinery_cost
Data type: float64
Unique values: 1023
Missing values: 0
machinery_cost
15000.0    5301
25000.0    4937
20000.0    4322
10000.0    4253
12000.0    3646
0.0        2159
16000.0    1854
35000.0    1797
8000.0     1618
18000.0    1387
14000.0    1247
9000.0      964
5000.0      949
50000.0     931
30000.0     903
Name: count, dtype: int64

==================================================
Column: maintenance_cost
Data type: float64
Unique values: 335
Missing values: 0
maintenance_cost
0.0        32568
2000.0      5508
5000.0      2411
1000.0      2319
3000.0      2091
2500.0      1887
4000.0      1462
500.0       1399
10000.0     1090
1500.0       880
8000.0       644
6000.0       603
3500.0       407
12000.0      358
1200.0       283
Name: count, dtype: int64

==================================================
Column: finance_source1
Data type: object
Unique values: 5
Missing values: 15969
finance_source1
Own savings        34551
NaN                15969
Others              4118
Government fund     2254
Money lender         252
Bank loan            159
Name: count, dtype: int64

==================================================
Column: finance_source2
Data type: object
Unique values: 5
Missing values: 23688
finance_source2
Others             26572
NaN                23688
Own savings         5297
Money lender         922
Government fund      664
Bank loan            160
Name: count, dtype: int64

==================================================
Column: construction_subsidy
Data type: float64
Unique values: 567
Missing values: 0
construction_subsidy
0.0         47070
5000.0        642
100000.0      544
10000.0       367
3000.0        303
2000.0        229
180000.0      228
12000.0       227
20000.0       224
589000.0      208
123953.0      197
606000.0      195
4000.0        190
30000.0       182
6000.0        165
Name: count, dtype: int64

==================================================
Column: machinery_subsidy
Data type: float64
Unique values: 515
Missing values: 0
machinery_subsidy
0.0         46328
3000.0        605
5000.0        504
100000.0      480
159366.0      404
2000.0        385
10000.0       343
35000.0       310
1000.0        273
150000.0      271
145285.0      248
141105.0      244
50000.0       220
158000.0      210
20000.0       198
Name: count, dtype: int64

==================================================
Column: scheme_status
Data type: object
Unique values: 3
Missing values: 0
scheme_status
In-Use                    51194
Temporarily Not in use     5342
Permanently Not in use      767
Name: count, dtype: int64

==================================================
Column: not_in_use_years
Data type: float64
Unique values: 7
Missing values: 51194
not_in_use_years
NaN    51194
1.0     2225
2.0     1714
0.0     1408
3.0      240
6.0      221
5.0      198
4.0      103
Name: count, dtype: int64

==================================================
Column: status_reason_temporarily
Data type: object
Unique values: 6
Missing values: 51961
status_reason_temporarily
NaN                                        51961
Any other reason                            3332
Mechanical break down                       1196
Non availability of adequate power/fuel      328
Lack of maintenance                          318
Less discharge of water                      165
Non availability of finance                    3
Name: count, dtype: int64

==================================================
Column: status_reason_permanently
Data type: object
Unique values: 7
Missing values: 56536
status_reason_permanently
NaN                                                56536
Due to other reasons                                 455
Destroyed beyond repair                              251
Dried up                                              36
Due to salinity                                       14
Due to sea water intrusion                             4
Due to industrial effluents                            4
Availability of major medium irrigation project        3
Name: count, dtype: int64

==================================================
Column: water_distribution_method
Data type: object
Unique values: 7
Missing values: 767
water_distribution_method
Surface pipe                             22690
Open Water Channel (unlined / Kutcha)    18596
Other                                    10832
Open Water Channel (lined / Pucca)        2241
Under ground pipe                         2057
NaN                                        767
Sprinkler                                   60
Drip                                        60
Name: count, dtype: int64

==================================================
Column: lifting_device_type
Data type: object
Unique values: 5
Missing values: 748
lifting_device_type
Centrifugal Pump    36890
Submersible pump    11950
Others               4793
Turbine/Jet pump     1806
Manual/animal        1116
NaN                   748
Name: count, dtype: int64

==================================================
Column: energy_source
Data type: object
Unique values: 7
Missing values: 748
energy_source
Diesel           27323
Electric         18689
Solar             8678
Manual/animal     1116
NaN                748
Others             702
Wind Mills          25
Natural             22
Name: count, dtype: int64

==================================================
Column: horse_power_of_lifting_device
Data type: float64
Unique values: 92
Missing values: 1919
horse_power_of_lifting_device
5.0     24491
2.0     14848
3.0     10667
NaN      1919
1.5      1455
7.5       743
4.0       693
1.0       569
20.0      505
2.5       312
3.5       252
10.0      140
15.0      130
7.0       120
30.0       66
Name: count, dtype: int64

==================================================
Column: pump_operating_days_kharif_season
Data type: float64
Unique values: 123
Missing values: 1907
pump_operating_days_kharif_season
30.0    9326
0.0     7480
60.0    6385
20.0    3374
90.0    2513
80.0    2440
40.0    2320
50.0    1963
25.0    1925
NaN     1907
2.0     1756
45.0    1654
10.0    1319
15.0    1204
70.0    1002
Name: count, dtype: int64

==================================================
Column: pump_operating_days_rabi_season
Data type: float64
Unique values: 140
Missing values: 1907
pump_operating_days_rabi_season
60.0     11468
90.0      7074
30.0      3009
50.0      2802
80.0      2583
100.0     2516
0.0       2488
NaN       1907
20.0      1689
40.0      1649
45.0      1632
120.0     1389
2.0       1317
10.0      1308
70.0      1307
Name: count, dtype: int64

==================================================
Column: pump_operating_days_perennial_crop
Data type: float64
Unique values: 72
Missing values: 1907
pump_operating_days_perennial_crop
0.0     49136
NaN      1907
30.0      963
20.0      832
10.0      719
15.0      464
40.0      454
2.0       402
1.0       303
8.0       289
5.0       284
45.0      227
60.0      205
7.0       127
50.0      125
Name: count, dtype: int64

==================================================
Column: pump_operating_days_other_season
Data type: float64
Unique values: 82
Missing values: 1907
pump_operating_days_other_season
0.0     39391
20.0     5056
30.0     1923
10.0     1919
NaN      1907
60.0      878
15.0      802
1.0       781
5.0       562
50.0      451
45.0      442
25.0      319
2.0       318
40.0      293
90.0      247
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_kharif_season
Data type: float64
Unique values: 53
Missing values: 1907
avg_pumping_per_day_kharif_season
6.0     12234
3.0      7529
0.0      7477
4.0      7277
5.0      6702
2.0      5314
8.0      4207
7.0      2254
NaN      1907
1.0       891
9.0       461
10.0      450
20.0      117
15.0       95
12.0       93
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_rabi_season
Data type: float64
Unique values: 64
Missing values: 1907
avg_pumping_per_day_rabi_season
6.0     12553
5.0      7281
4.0      6582
8.0      6462
3.0      4941
2.0      3781
7.0      3418
0.0      2489
9.0      2383
NaN      1907
10.0     1577
1.0      1430
12.0      812
11.0      806
6.5       209
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_perennial_crop
Data type: float64
Unique values: 29
Missing values: 1907
avg_pumping_per_day_perennial_crop
0.0     49135
NaN      1907
2.0      1511
3.0      1304
1.0      1125
4.0      1000
5.0       628
6.0       304
7.0       148
8.0        97
10.0       69
9.0        17
20.0       10
12.0        9
2.5         9
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_other_season
Data type: float64
Unique values: 36
Missing values: 1908
avg_pumping_per_day_other_season
0.0     39404
3.0      3398
2.0      3250
6.0      2522
4.0      2127
1.0      1978
NaN      1908
5.0      1380
2.5       581
8.0       251
7.0       200
10.0      104
9.0        37
20.0       29
3.5        25
Name: count, dtype: int64

==================================================
Column: located_in_command_area
Data type: object
Unique values: 2
Missing values: 0
located_in_command_area
No     57157
Yes      146
Name: count, dtype: int64

==================================================
Column: name_of_mmi_project
Data type: object
Unique values: 24
Missing values: 57142
name_of_mmi_project
NaN                             57142
JAMUNA IRRIGATION SCHEME           55
JAMUNA                             28
BOROLIA                            15
SONAI                              12
AMRENG                              8
BHUMKI FIS                          6
CHAMPAMATI                          5
BOROLIA IRRIGATION SCHEME           4
DHANSIRI IRRIGATION PROJECT         4
SUKLA                               4
RUPAHI                              3
BORDIKORAI IRRIGATION SCHEME        2
DHANSIRI                            2
DEKADONG FIS                        2
Name: count, dtype: int64

==================================================
Column: scheme_in_command_area_reason
Data type: object
Unique values: 4
Missing values: 57157
scheme_in_command_area_reason
NaN                                                         57157
Other reasons                                                  76
Water not available up to field from major/medium scheme       38
Water available but not adequate for irrigation                25
Water available but not useable for irrigation                  7
Name: count, dtype: int64

==================================================
Column: only_recharge_ground_water
Data type: object
Unique values: 2
Missing values: 0
only_recharge_ground_water
No     56143
Yes     1160
Name: count, dtype: int64

==================================================
Column: culturable_command_area
Data type: float64
Unique values: 372
Missing values: 0
culturable_command_area
2.00     15044
4.00     10857
1.00      7842
3.00      5751
1.50      2018
5.00      1925
0.00      1825
0.50       855
10.00      813
2.50       639
6.00       575
1.20       501
0.80       494
1.33       473
0.53       417
Name: count, dtype: int64


In [13]:
"""
vilage name may need to be dropped 
s no of schemes may need to be dropped
scheme type most data is tube well 
Khashar number needs to be converted to int
location particular may need to be dropped
social status needs missing value analysis
gender needs missing value analysis
scheme diamaeter has missing values
bore depth has mostly missng values find MCAR MAR MNAR
machinery_cost, maintenance_cost are calculated after finding construction_cost so they need to be dropped
finance source 1 nad 2 need to be merged
construction_subsidy, machinery_subsidy need to be analysed and may need to be dropped 
scheme_status may not be useful 
not_in_use_years need to analyse MCAR MAR
status_reason_temporarily may need to be dropped
status_reason_permanently may need to be dropped
water_distribution_method, lifting_device_type, energy_source, horse_power_of_lifting_device handle missing
pump_operating_days_kharif_season, pump_operating_days_rabi_season, pump_operating_days_perennial_crop, pump_operating_days_other_season handle missing nad check data type
avg_pumping_per_day_kharif_season, avg_pumping_per_day_rabi_season, avg_pumping_per_day_perennial_crop, avg_pumping_per_day_other_season handle missing
located_in_command_area may be useless 
name_of_mmi_project, scheme_in_command_area_reason may need to be dropped
only_recharge_ground_water analyze ma need to remove
ipu_perennial_crop, ipu_other_season, under_utilised_selection handle missing
under_utilisation_reason may need to be dropped 
captured_in_previous_census, handle missing
"""
print()

# Removing Columns that are Dependent on Constuction_Cost

In [14]:
cols = [
    'pump_operating_days_kharif_season',
    'pump_operating_days_rabi_season',
    'pump_operating_days_perennial_crop',
    'pump_operating_days_other_season',
    'avg_pumping_per_day_kharif_season',
    'avg_pumping_per_day_rabi_season',
    'avg_pumping_per_day_perennial_crop',
    'avg_pumping_per_day_other_season',
    'ipc_kharif_season',
    'ipc_rabi_season',
    'ipc_perennial_crop',
    'ipc_other_season',
    'ipc_total',
    'ipu_kharif_season',
    'ipu_rabi_season',
    'ipu_perennial_crop',
    'ipu_other_season',
    'ipu_total'
]

df.drop(columns=cols, inplace=True)

In [15]:
import os
os.makedirs("./data", exist_ok=True)

df.drop(columns=["serial_no", "state_name"], inplace=True)
df.to_csv("./data/01_Data_Exploration.csv", index=False)